# Настройки мобов
mobs:
  zombie:
    name: "Зомби"
    type: "ZOMBIE"
    health: 5
    speed: 0.15
    reward: 5
  skeleton:
    name: "Скелет"
    type: "SKELETON"
    health: 10
    speed: 0.25
    reward: 10
  chicken:
    name: "Курица"
    type: "CHICKEN"
    health: 2
    speed: 0.35
    reward: 3
  evoker:
    name: "БОСС"
    type: "EVOKER"
    health: 100
    speed: 0.05
    reward: 100

# Настройки башен
towers:
  basic:
    name: "Базовая башня"
    damage: 1
    attack_speed: 2.0
    range: 3
    cost: 10
    material: "COBBLESTONE"
  medium:
    name: "Средняя башня"
    damage: 2
    attack_speed: 1.0
    range: 2
    cost: 20
    material: "IRON_BLOCK"
  advanced:
    name: "Продвинутая башня"
    damage: 5
    attack_speed: 0.5
    range: 1
    cost: 40
    material: "DIAMOND_BLOCK"

# Путь мобов
path:
  start: "973.5,151,989.5"
  end: "979.5,151,1002.5"
  points:
    - "973.5,151,1002.5"
    - "976.5,151,1002.5"
    - "976.5,151,989.5"
    - "979.5,151,989.5"
    - "979.5,151,1002.5"

# Настройки игры
game:
  start_money: 50
  start_lives: 10